#!/bin/sh

DAEMON=/usr/bin/aesdsocket
DAEMON_OPTS="-d"
NAME=aesdsocket
DESC="AESD Socket Server"
PIDFILE=/var/run/$NAME.pid

start() {
    echo "Starting $DESC: $NAME"
    if [ -f $PIDFILE ]; then
        echo "$DESC is already running."
    else
        $DAEMON $DAEMON_OPTS &
        sleep 1
        PID=$(pgrep -f "$DAEMON $DAEMON_OPTS")
        if [ -n "$PID" ]; then
            echo $PID > $PIDFILE
            echo "$DESC started with PID $PID"
        else
            echo "Failed to start $DESC"
        fi
    fi
}

stop() {
    echo "Stopping $DESC: $NAME"
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        kill -15 $PID
        rm -f $PIDFILE
        echo "$DESC stopped"
    else
        echo "$DESC is not running."
    fi
}

status() {
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        if [ -e /proc/$PID ]; then
            echo "$DESC is running (PID $PID)"
        else
            echo "$DESC is not running, but pidfile exists"
        fi
    else
        echo "$DESC is not running"
    fi
}

restart() {
    stop
    sleep 4
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
